PCB3.SIG - Signal Integrity Report
----------------------------------


Designator to Component Type Specification
------------------------------------------
Warning! No designator to component type mapping defined.All components considered as type IC.


Power Supply Nets
-----------------
Warning! No supply nets defined. Results may be unreliable.


ICs with valid models
---------------------


ICs With No Valid Model
-----------------------
C4                  100N                Closest match in library will be used
L1                  INDUCTOR            Closest match in library will be used
R29                 2K2                 Closest match in library will be used
R30                 2K2                 Closest match in library will be used
R31                 2K2                 Closest match in library will be used
R32                 2K2                 Closest match in library will be used
R33                 2K2                 Closest match in library will be used
R34                 2K2                 Closest match in library will be used
R35                 2K2                 Closest match in library will be used
R36                 2K2                 Closest match in library will be used
R37                 2K2                 Closest match in library will be used
R38                 2K2                 Closest match in library will be used
R39                 2K2                 Closest match in library will be used
R40                 2K2                 Closest match in library will be used
R41                 2K2                 Closest match in library will be used
R42                 2K2                 Closest match in library will be used
R43                 2K2                 Closest match in library will be used
R44                 2K2                 Closest match in library will be used
R45                 2K2                 Closest match in library will be used
R46                 2K2                 Closest match in library will be used
R47                 2K2                 Closest match in library will be used
R48                 2K2                 Closest match in library will be used
R49                 2K2                 Closest match in library will be used
R50                 2K2                 Closest match in library will be used
R51                 2K2                 Closest match in library will be used
R52                 2K2                 Closest match in library will be used
R53                 2K2                 Closest match in library will be used
R54                 2K2                 Closest match in library will be used
R55                 2K2                 Closest match in library will be used
R63                 2K2                 Closest match in library will be used
R65                 2K2                 Closest match in library will be used
R70                 2K2                 Closest match in library will be used
R71                 2K2                 Closest match in library will be used
R72                 2K2                 Closest match in library will be used
R73                 2K2                 Closest match in library will be used
R74                 1K                  Closest match in library will be used
R75                 10K                 Closest match in library will be used
R76                 2K2                 Closest match in library will be used
R77                 2K2                 Closest match in library will be used
C2                  12P                 Closest match in library will be used
C3                  12P                 Closest match in library will be used
C6                  100N                Closest match in library will be used
C8                  100N                Closest match in library will be used
Q1                  3904                Closest match in library will be used
RN2                 4K7                 Closest match in library will be used
SLOT102             100PIN              Closest match in library will be used
SRAM                65LV256AL_SOP       Closest match in library will be used
C14                 100N                Closest match in library will be used
E2                  AT24C128            Closest match in library will be used
C0                  CAP                 Closest match in library will be used
C1                  100N                Closest match in library will be used
C10                 100N                Closest match in library will be used
C11                 100N                Closest match in library will be used
C12                 100N                Closest match in library will be used
C16                 100N                Closest match in library will be used
C17                 100N                Closest match in library will be used
C18                 100N                Closest match in library will be used
C19                 100N                Closest match in library will be used
C20                 100N                Closest match in library will be used
C21                 100N                Closest match in library will be used
C23                 100N                Closest match in library will be used
C24                 100N                Closest match in library will be used
R0                  RES1                Closest match in library will be used
R1                  RES1                Closest match in library will be used
R2                  30K                 Closest match in library will be used
R3                  60K                 Closest match in library will be used
R4                  1K                  Closest match in library will be used
R5                  30K                 Closest match in library will be used
R6                  60K                 Closest match in library will be used
R13                 2K2                 Closest match in library will be used
R14                 2K2                 Closest match in library will be used
R15                 2K2                 Closest match in library will be used
R16                 2K2                 Closest match in library will be used
R17                 2K2                 Closest match in library will be used
R18                 2K2                 Closest match in library will be used
R19                 2K2                 Closest match in library will be used
R20                 2K2                 Closest match in library will be used
R21                 2K2                 Closest match in library will be used
R22                 2K2                 Closest match in library will be used
R23                 2K2                 Closest match in library will be used
R24                 2K2                 Closest match in library will be used
R25                 2K2                 Closest match in library will be used
R26                 2K2                 Closest match in library will be used
R27                 2K2                 Closest match in library will be used
R28                 2K2                 Closest match in library will be used
R56                 2K2                 Closest match in library will be used
R57                 2K2                 Closest match in library will be used
R58                 2K2                 Closest match in library will be used
RN1                 4K7                 Closest match in library will be used
RN23                0                   Closest match in library will be used
RN19                0                   Closest match in library will be used
RN17                0                   Closest match in library will be used
C25                 100N                Closest match in library will be used
C26                 100N                Closest match in library will be used
C27                 100N                Closest match in library will be used
C28                 100N                Closest match in library will be used
C29                 100N                Closest match in library will be used
C30                 100N                Closest match in library will be used
C31                 100N                Closest match in library will be used
C32                 100N                Closest match in library will be used
L2                  Comment             Closest match in library will be used
C93                 10uF                Closest match in library will be used
RN22                0                   Closest match in library will be used
RN21                0                   Closest match in library will be used
RN20                0                   Closest match in library will be used
RN18                0                   Closest match in library will be used
RN16                0                   Closest match in library will be used
RN15                0                   Closest match in library will be used
04                  04                  Closest match in library will be used
68013               68013               Closest match in library will be used
C5                  100N                Closest match in library will be used
C7                  100N                Closest match in library will be used
C9                  100N                Closest match in library will be used
C13                 100N                Closest match in library will be used
C15                 100N                Closest match in library will be used
C22                 100N                Closest match in library will be used
COM1                DB9                 Closest match in library will be used
COM2                3PIN                Closest match in library will be used
E1                  AT24C128            Closest match in library will be used
EPM240              EPM240T100          Closest match in library will be used
LED0                LED                 Closest match in library will be used
LED1                LED                 Closest match in library will be used
LED2                LED                 Closest match in library will be used
LED3                LED                 Closest match in library will be used
LED4                LED                 Closest match in library will be used
LED5                LED                 Closest match in library will be used
LED6                LED                 Closest match in library will be used
LED7                LED                 Closest match in library will be used
LED8                LED                 Closest match in library will be used
LED9                LED                 Closest match in library will be used
LED10               LED                 Closest match in library will be used
LED11               LED                 Closest match in library will be used
LED12               LED                 Closest match in library will be used
LED13               LED                 Closest match in library will be used
LED14               LED                 Closest match in library will be used
LED15               LED                 Closest match in library will be used
LED16               LED                 Closest match in library will be used
LED17               LED                 Closest match in library will be used
LED18               LED                 Closest match in library will be used
LED19               LED                 Closest match in library will be used
LED20               LED                 Closest match in library will be used
LED21               LED                 Closest match in library will be used
LED22               LED                 Closest match in library will be used
LED23               LED                 Closest match in library will be used
LED24               LED                 Closest match in library will be used
LED25               LED                 Closest match in library will be used
LED26               LED                 Closest match in library will be used
LED27               LED                 Closest match in library will be used
LED28               LED                 Closest match in library will be used
LED29               LED                 Closest match in library will be used
LED30               LED                 Closest match in library will be used
LED31               LED                 Closest match in library will be used
LED32               LED                 Closest match in library will be used
LED33               LED                 Closest match in library will be used
LED34               LED                 Closest match in library will be used
LED35               LED                 Closest match in library will be used
LED36               LED                 Closest match in library will be used
LED37               LED                 Closest match in library will be used
LED38               LED                 Closest match in library will be used
LED39               LED                 Closest match in library will be used
LED40               LED                 Closest match in library will be used
LED41               LED                 Closest match in library will be used
LED42               LED                 Closest match in library will be used
LED43               LED                 Closest match in library will be used
LED44               LED                 Closest match in library will be used
LED45               LED                 Closest match in library will be used
LED46               LED                 Closest match in library will be used
LED3V3              LED                 Closest match in library will be used
LED5V               LED                 Closest match in library will be used
MAX3232             MAX3232             Closest match in library will be used
P1                  LM1117              Closest match in library will be used
R11                 2K2                 Closest match in library will be used
R12                 2K2                 Closest match in library will be used
R64                 2K2                 Closest match in library will be used
RN3                 220                 Closest match in library will be used
RN4                 220                 Closest match in library will be used
RN5                 220                 Closest match in library will be used
RN6                 220                 Closest match in library will be used
RN7                 220                 Closest match in library will be used
RN8                 220                 Closest match in library will be used
RN9                 220                 Closest match in library will be used
RN10                220                 Closest match in library will be used
RN11                220                 Closest match in library will be used
RN12                220                 Closest match in library will be used
RN13                220                 Closest match in library will be used
S1                  SW DIP-2            Closest match in library will be used
SLOT100             100PIN              Closest match in library will be used
SLOT101             100PIN              Closest match in library will be used
Slot2               40PIN               Closest match in library will be used
Slot3               40PIN               Closest match in library will be used
Slot4               40PIN               Closest match in library will be used
USB                 USB_DEVICE          Closest match in library will be used
Y1                  24M                 Closest match in library will be used
COM3                DB9                 Closest match in library will be used
R78                 0                   Closest match in library will be used
C94                 10uF                Closest match in library will be used


